Задание ИТ №2
Sversim/Doctor-sAppointment pull request #1
Opened 2022-10-09 01:43 UTC by Sversim

2022-10-09 09:46 UTC, Vixorem requested changes

2022-10-09 09:46 UTC, Vixorem commented on MyFirstClassLibrary/User.cs
> +        public User(string login, string password)
А зачем такой конструктор, где только половина полей заполняется

2022-10-09 09:46 UTC, Vixorem commented on ClinicTests/UserTests.cs
> +    public class UserTests
Кажется, что мало кейсов

2022-10-09 10:02 UTC, Sversim commented on MyFirstClassLibrary/User.cs
> +        public User(string login, string password)
Сейчас поправим

2022-10-09 10:03 UTC, Sversim commented on ClinicTests/UserTests.cs
> +    public class UserTests
Пока кажется, что нечего тестировать

2022-10-10 11:55 UTC, Vixorem approved these changes

2022-10-11 00:24 UTC, foggy21 commented on MyFirstClassLibrary/UserInteractor.cs
> +        public bool IsUserExists(string login, string password)
Тут не должна быть обертка в Result?

2022-10-11 00:24 UTC, foggy21 commented on MyFirstClassLibrary/User.cs
>          public User()
Я, конечно, душнить не хочу, но зачем тут пустой конструктор?

2022-10-11 00:24 UTC, foggy21 commented on ClinicTests/UserTests.cs
> +            Assert.Equal("������������ � ����� ������� �� ������", res.Error);
И, наверное, нужно что-то сделать с кодировкой. У меня просто тут непонятные символы в строке.

2022-10-11 00:24 UTC, foggy21 commented on ClinicTests/UserTests.cs
> +        public void UserNotFound_Fail()
Можно ещё сделать тест на успешный поиск юзера по логину, тест при котором происходит добавление юзера с пустым логином/паролем, тест на успешное добавление юзера. И у тебя нет тестов, которые покрывают метод IsUserExists.

2022-10-17 03:23 UTC, merged