Data base
Sversim/Doctor-sAppointment pull request #3
Opened 2022-11-13 09:02 UTC by Sversim

Базовая логика работы с БД

2022-11-16 08:29 UTC, DeadDogDance approved these changes

2022-11-18 10:52 UTC, Vixorem requested changes
Концептуально все норм. Просто некоторые замечания

2022-11-18 10:52 UTC, Vixorem commented on ClinicTests/AppointmentTests.cs
> +    public class AppointmentTests
Если проверять реальную роботоспособность методов, то конечно такие себе тесткейсы; можно было бы через МОКи подготовить разные данные, в уме посчитать, что должно возвращаться и потом в тесткейсах проверить, так ли оно на самом деле

2022-11-18 10:52 UTC, Vixorem commented on DataBaseModerator/AppointmentRepository.cs
> +                .Join(_context.Medics,
Ты вроде первый, у кого я увидел джойн, клево)

2022-11-18 10:52 UTC, Vixorem commented on DataBaseModerator/AppointmentRepository.cs
> +                    // Магические числа:
Ох лучше какие то константы сделать, так вставлять умножения на ходу не оч

2022-11-18 10:52 UTC, Vixorem commented on DataBaseModerator/AppointmentRepository.cs
> +                // но пока не вполне понятно, что именно требуется
Ну, надо получить даты, кусками по полчаса. Допустим, сегодня у врача  заняты часы с 13:00 по 18:00. Время работы врача с 11:00 по 18:00. Получается нужно будет вернуть куски начиная с 11:00 по 13:00

2022-11-18 10:52 UTC, Vixorem commented on DataBaseModerator/UserModel.cs
> +        public UserModel(int id, string phoneNumber, string fullName, string login, string password, Role userRole)
Не уверен, но боюсь, что именно в моделях для EF, конструкторы могут только мешать. Лучше просто оставить автосвойства

2022-11-18 10:52 UTC, Vixorem commented on MyFirstClassLibrary/Medic.cs
> +            // TODO Здесь должен быть перевод int в существующую в таблице специализацию, видимо
Лучше поубирать конструкторы. Под капотом EF по идее создаст в этом случае foreign key чтоб связать таблицу медика и специализации

2022-11-18 10:52 UTC, Vixorem commented on MyFirstClassLibrary/Timetable.cs
> +        public Timetable()
Пустой конструктор не нужен

2023-01-14 08:18 UTC, merged